name: build-app

on:
  push:
    branches:
      - develop

jobs:

  build_app:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: cache frontend dependencies
        id: cache-frontend-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-frontend-npm
        with:
          path: ./frontend/node_modules/
          key: cache-frontend-npm-${{ hashFiles('frontend/package-lock.json') }}

      - name: install frontend dependencies (if not cached)
        if: steps.cache-frontend-npm.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: npm ci

      - name: build frontend
        working-directory: ./frontend
        run: npm run build

      - name: build electron app (win 64)
        run: |
          docker run --rm -i \
          --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          --env GH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -v ${PWD}:/project \
          -v ${PWD##*/}-node-modules:/project/node_modules \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          bash -c "npm i && npm run build:win"

      - name: build electron app (win 32)
        run: |
          docker run --rm -i \
          --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
          --env ELECTRON_CACHE="/root/.cache/electron" \
          --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" \
          --env GH_TOKEN=${{ secrets.GITHUB_TOKEN }} \
          -v ${PWD}:/project \
          -v ${PWD##*/}-node-modules:/project/node_modules \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          bash -c "npm i && npm run build:win32"

      - name: store the app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-installers
          path: |
            ./dist/*.exe
